
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kriti
 */
public class UpdateHma extends javax.swing.JFrame {

    /**
     * Creates new form UpdateHma
     */
    public UpdateHma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        concText = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        wardComboBox = new javax.swing.JComboBox<>();
        paraComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Select Ward :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Select Parameter :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Enter Concentration (mg/kg) : ");

        concText.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        wardComboBox.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        wardComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        wardComboBox.setSelectedIndex(-1);
        wardComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardComboBoxActionPerformed(evt);
            }
        });

        paraComboBox.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        paraComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadmium", "Cobalt", "Lead", "Nickel", "Manganese", "Chromium", "Copper", "Iron", "Zinc" }));
        paraComboBox.setSelectedIndex(-1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("Updation Details");

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(concText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(wardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(paraComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(updateBtn)
                        .addGap(115, 115, 115)
                        .addComponent(backBtn)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(wardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(paraComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(concText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(updateBtn))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wardComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardComboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new UpdateHma().setVisible(false);
        this.dispose();
        new Options().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try{ 
        String msg=(String)paraComboBox.getSelectedItem();
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
         
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://desktop-tbno2fe\\sqlexpress:1433;databaseName=Waste_Management;integratedSecurity=true;");
                Statement st = conn.createStatement();
                switch(msg)
                {
                    case "Cadmium": st.executeUpdate("update Heavy_Metals set Cadmium='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                        break;
                    case "Cobalt": st.executeUpdate("update Heavy_Metals set Cobalt='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                        break;
                    case "Lead": st.executeUpdate("update Heavy_Metals set Lead='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                        break;
                    case "Nickel": st.executeUpdate("update Heavy_Metals set Nickel='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                        break;
                    case "Manganese": st.executeUpdate("update Heavy_Metals set Manganese='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                        break;
                    case "Chromium": st.executeUpdate("update Heavy_Metals set Chromium='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                        break;
                    case "Copper": st.executeUpdate("update Heavy_Metals set Copper='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                        break;
                    case "Iron": st.executeUpdate("update Heavy_Metals set Iron='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                      break;
                   case "Zinc": st.executeUpdate("update Heavy_Metals set Zinc='"+concText.getText()+"' where Ward='"+(String)wardComboBox.getSelectedItem()+"'");
                }
                   JOptionPane.showMessageDialog(null, "Value Updated.");
                   wardComboBox.setSelectedIndex(-1);
                   paraComboBox.setSelectedIndex(-1);
                   concText.setText("");
       }catch(Exception ex)
          {
              JOptionPane.showMessageDialog(null, ex);
          }
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateHma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateHma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateHma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateHma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateHma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField concText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> paraComboBox;
    private javax.swing.JButton updateBtn;
    private javax.swing.JComboBox<String> wardComboBox;
    // End of variables declaration//GEN-END:variables
}
